apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue-frontend
  template:
    metadata:
      labels:
        app: vue-frontend
    spec:
      containers:
        - image: yourregistry.azurecr.io/vue-frontend:latest  # Specify the full image name
          name: vue-frontend
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /shared-data
              name: shared-volume
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-volume
