apiVersion: v1
kind: Service
metadata:
  name: vue-frontend
spec:
  ports:
    - name: "3000"
      port: 80
      targetPort: 3000
  selector:
    app: vue-frontend  # Match the labels in your Deployment
