apiVersion: v1
kind: Service
metadata:
  name: flask-backend
spec:
  ports:
    - name: "5000"
      port: 80  # You can change this port to 80 if your container listens on port 5000
      targetPort: 5000
  selector:
    app: flask-backend  # Match the labels in your Deployment
