apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
        - image: yourregistry.azurecr.io/flask-backend:latest  # Specify the full image name
          name: flask-backend
          ports:
            - containerPort: 5000
          resources: {}
