apiVersion: v1
kind: Service
metadata:
  name: custom-nginx
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    app: custom-nginx  # Match the labels in your Deployment
