# backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: $(imagePullSecret)
      containers:
        - name: backend-container
          image: backend-image:$(tag)
          ports:
            - containerPort: 80